---
- hosts: localhost
  name: test connection snow
  gather_facts: False
  connection: local
  tasks:
  - name: "Grab a User record"
    snow_record:
      username: snow username
      password: snow user password
      instance: service-now instancename 
      state: present
      number: xxxxxxx
      table: sys_user
      lookup_field: xxxxx
